name: Factions
description: "Core for OPFactions"
author: Taco
website: "https://github.com/TacoError"

api: "4.0.0"
version: 1.0.0
main: Taco\Factions\Main
load: POSTWORLD

depend:
  - WFT

permissions:
  core.groups:
    default: op
  core.permissions:
    default: op
  core.kits:
    default: op
  core.money:
    default: op
  core.crates:
    default: op