name: Factions
description: "Core for OPFactions"
author: Taco
website: "https://github.com/TacoError"

api: "4.0.0"
version: 1.0.0
main: Taco\Factions\Main

permissions:
  core.groups:
    default: op
  core.permissions:
    default: op